### ISSUE TITLE
erraneous rendering in full_description

### ISSUE THREAD

**Issue by yashpalgoyal1304** [tenzap/exif-thumbnail-adder#10]
issue in the full_description.txt in using the html `<a>` tag. See: https://f-droid.org/packages/com.exifthumbnailadder.app/

https://github.com/tenzap/exif-thumbnail-adder/blob/master/fastlane/metadata/android/en-US/full_description.txt

![vivaldi_5nlziaA1W0](https://user-images.githubusercontent.com/19423063/120533545-765f5200-c3fe-11eb-8c02-3b361a6bfef5.png)

**Comment by tenzap** [comment]
Thank you for that report. I already created a issue for that on fdroid website repo.
Only the website is problematic. In the app everything is fine.

https://gitlab.com/fdroid/fdroid-website/-/issues/570
