### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Agne-Mathetes** [tenzap/exif-thumbnail-adder#16]
App suddenly crashes without message with latest Fdroid update.

I have tried to set "Skip from Exiv2 error level" to "Never skip, even in case of error." with no improvement. App window just disappears after a while in front of my eyes. Not sure what is going on.

Version: 0.9.5

My system: Huawei P20 Lite, Android 9.1.0.372
Free RAM: 754 MB / 3758 MB
Free storage: 10.24 GB / 50.58 GB

App permissions:
Write storage: yes
Exclude from battery optimization: yes
Allow autostart: yes
Allow to run in background: yes
Allow secondary start: yes

**Comment by tenzap** [comment]
Thanks for you report. Does it happen while processing files? Always at the same point? Is it a random crash? You say there was no problem with 0.9.4 ?

**Comment by tenzap** [comment]
I also face such a crash on a given picture.
- 0.9.5 built by F-droid -> crashes `Abort message: 'No pending exception expected: java.lang.ClassNotFoundException: com.exifthumbnailadder.app.Exiv2ErrorException`
- 0.9.5 built by android studio on my system -> no crash, the app reports correctly that there is an error in the file.

hmmm...

**Comment by tenzap** [comment]
fixed in 0.9.8
