### ISSUE TITLE
Old JPEGs missing thumbnails

### ISSUE THREAD

**Issue by PMPreston** [tenzap/exif-thumbnail-adder#24]
I own a Xiaomi Redmi Note 8 Pro running MIUI 12.5.7 (Android 11?), your program EXIF Thumbnail Adder (ETA) works with new JPEGs taken with the camera stored in DCIM folder but if I use it on old JPEGs stored in Pictures folder it doesn't work.  The JPEGs are allegedly converted by ETA but upon examination there is no JPEG thumbnail in Resources tab because no tab is created ( Right-click file choose Properties to find this tab if exists).

Paul Preston, Dagenham, UK

**Comment by tenzap** [comment]
Can you provide a sample input picture please?

**Comment by PMPreston** [comment]
Hi,



Your e-mail:-

Thanks. I haven't found your email.

For me the thumbnail is added. If checked with both exiv2 and libexif libraries. I then used the app exif tool to check the presence of thumbnail in the file. It is there.

What do you use to check the presence of the thumbnail?




Here is the original email again.  All I get is a generic icon because there is no Resources tab generated so no thumbnail? Your program confirms it has converted the files but no thumbnail? I just use Windows 10 to display the thumbnails when smartphone attached, I do not understand what you said as I am not technically minded. The Resources tab can be checked by right-clicking a file an selecting Properties.

Thanks
Paul Preston
email = ***@***.***
________________________________

**Comment by tenzap** [comment]
> The Resources tab can be checked by right-clicking a file an selecting Properties.

Is this on Windows 10? You are in the explorer, right click on the file, then click properties? I don't have resource tab either, on none of my pictures, but the windows picture importer and other tools still show the thumbnail.

I have 4 tabs: general, security, details, previous versions.

**Comment by tenzap** [comment]
Ok I found it, the resource tab is Indeed shown on some pictures when navigating the phone (and not the disk) and on yours it's not. And it seems the thumbnails are not found as you say.

**Comment by tenzap** [comment]
This should be fixed in 0.9.13. It will be available in F-Droid in a couple of days.

**Comment by PMPreston** [comment]
Hi

Yesterday (02 May 2022) I accessed F-Droid to update EXIF-Thumbnail-adder but it's still stuck on version 0.9.12.
I did a bit of research and found out that you are up to version 0.9.15. How about uploading the newest version to F-DROID?



Thanks
Paul Preston.
________________________________

**Comment by PMPreston** [comment]
Hello,

As requested an 'Old JPEG' (bad picture of me!).

Thank you for the quick response.
Paul Preston
e-mail: ***@***.***
________________________________
