### ISSUE TITLE
Further to Issue 24 I replied with picture by email

### ISSUE THREAD

**Issue by PMPreston** [tenzap/exif-thumbnail-adder#25]
Issue 24, I replied with picture by email.

However I attach a picture to solve this issue 24. Sorry for misunderstanding.

Thank you
Paul Preston
email = P_M_Preston@hotmail.com

![WIN_20170122_12_11_27_Pro](https://user-images.githubusercontent.com/101560613/160108951-e1e68094-0044-4e38-a23e-7b767ea18b28.jpg)

**Comment by tenzap** [comment]
Thanks. I haven't found your email.

For me the thumbnail is added. If checked with both exiv2 and libexif libraries. I then used the app exif tool to check the presence of thumbnail in the file. It is there.

What do you use to check the presence of the thumbnail?
