### ISSUE TITLE
ETA 0.9.15 files that did not convert

### ISSUE THREAD

**Issue by PMPreston** [tenzap/exif-thumbnail-adder#28]
Hi,

Have recently downloaded EXIF-Thumbnail-Adder (ETA) version 0.9.15 from F-Droid it's very good, converted all my JPEGs except those attached.  The icon files are not that important but would be nice if ETA could convert them as well as JPEGs but not essential.

The five JPEGs do not convert for some reason could not determine I thought you might want to have a look?

Thanks
Paul Preston
e-mail : P_M_Preston@hotmail.com

Please find attached zip with the 12 files:-

[ETA files not converted 20220511.zip](https://github.com/tenzap/exif-thumbnail-adder/files/8669452/ETA.files.not.converted.20220511.zip)
m

**EDIT:** [Input files](https://github.com/tenzap/exif-thumbnail-adder/files/8676974/ETA.not.converted.RAW.20220512.zip) (from #29)

**Comment by tenzap** [comment]
- ETA only supports JPEGs, so there is no support for other file types

I have this output:
![image](https://user-images.githubusercontent.com/46226844/169279029-c74d8c06-eeff-44d4-be70-5e1d0ee8e933.png)

- Could you please be more precise on what you observe and what you expect for each picture? Maybe you should also report your settings.

**Comment by PMPreston** [comment]
Hi,

I get the same error messages though it says some of the JPEGs are 'Done' they display the generic icon not a thumbnail. All twelve .JPEGs and .ICOs I sent you produce generic icons not a thumbnail. I sent your processed files in issue #28 and raw before processing in issue #29.

Hope this clarifies.

Paul Preston
e-mail:- ***@***.***

________________________________
