### ISSUE TITLE
Colour choice makes text hard to read

### ISSUE THREAD

**Issue by lifers** [tenzap/exif-thumbnail-adder#3]
Version 0.9.4 fresh install
![Screenshot_2021-05-18-18-02-24-66.jpg](https://user-images.githubusercontent.com/61454123/118640724-858daf80-b803-11eb-9786-fefde000802b.jpg)

**Comment by tenzap** [comment]
Thank you for that report. Color & design are my weak points. I almost left all colors as they are by default with the example project created by android studio.

Are you using dark theme ?

I see that About is difficult to read, and also the white text on grey background.

Could you elaborate on what should be changed and may be suggest which colors to use ?

**Comment by tenzap** [comment]
On my phone with dark theme it is fine. What is your phone model, which android version ?
![Screenshot_2021-05-18-13-44-41-118_com exifthumbnailadder app](https://user-images.githubusercontent.com/46226844/118645709-8d3b5d00-b7df-11eb-9550-2220eecbe185.jpg)

**Comment by lifers** [comment]
My phone model is Oppo F9 Pro CPH1823, running Android 10, dark theme enabled. From your screenshot I think your phone shows the proper colouring, but mine doesn't.

**Comment by tenzap** [comment]
On emulated device it is like your screenshot. Would that output be ok ?
![Screenshot_1621362948](https://user-images.githubusercontent.com/46226844/118706915-3606ae00-b81a-11eb-92cc-a6181efb70f1.png)

**Comment by lifers** [comment]
> ![Screenshot_1621362948](https://user-images.githubusercontent.com/46226844/118706915-3606ae00-b81a-11eb-92cc-a6181efb70f1.png)

Yes, this output is ok.
