### ISSUE TITLE
App Crash on A13

### ISSUE THREAD

**Issue by locuturus** [tenzap/exif-thumbnail-adder#30]
Hello, both my Pixel 4a on the beta track and Xperia 5 iii on stable A13 crash immediately at app launch. From F- Droid, version 0.9.16

I've attached an Xperia logcat grep filtered for "exifthumbnail" but I'm open to tweaking that.

[logcat_exifthumbnail.txt](https://github.com/tenzap/exif-thumbnail-adder/files/10680186/logcat_exifthumbnail.txt)

**Comment by tenzap** [comment]
I guess this is fixed in 0.9.16.1
It's on Google play and Amazon appstore  and waiting for build on fdroid.
Does it fix your problem?

**Comment by locuturus** [comment]
That extra .1 release does seem to do the trick!
